version: "3.7"

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
        sh -c "yarn serve"
    container_name: vue-app
    restart: always
    ports:
      - "8888:8080"
    networks:
      - vue-network
networks:
  vue-network:
    driver: bridge
